#Arithmatic.py
a=int(input("Entet First Value :"))
b=int(input("Enter Second Value :"))
print("="*50)
print(" A R I T H M A T I C  O P E R A T O R S  ")
print("="*50)
print("Sum Of ({} And {}) = {}".format(a,b,a+b))
print("Sub Of ({} And {}) = {}".format(a,b,a-b))
print("Multli Of ({} And {}) = {}".format(a,b,a*b))
print("Div Of ({} And {}) = {}".format(a,b,a/b))
print("Integer Modulo Of ({} And {}) = {}".format(a,b,a//b))
print("Remainder Of ({} And {}) = {}".format(a,b,a%b))
print("Power Of ({} And {}) = {}".format(a,b,a**b))
print("="*50)