a=float(input("Enter Your First Value :" ))
b=float(input("Enter Your Second Value :" ))
print("#"*30)
print("Addition {} and {}={}".format(a,b,a+b))
print("-"*30)
print("Subtraction {} and {}={}".format(a,b,a-b))
print("-"*30)
print("Multiplication {} and {}={}".format(a,b,a*b))
print("-"*30)
print("Division {} and {}={}".format(a,b,a/b))
print("-"*30)
print("Floating Quetioint {} and {}={}".format(a,b,a//b))
print("-"*30)
print("Module {} and {}={}".format(a,b,a%b))
print("-"*30)
print("Exponention {} and {}={}".format(a,b,a**b))
print("#"*30)