# Program For Demonstrating Of Arithmatic Operators

print("-"*50)
a=float(input("Enter Your First Value :",))
b=float(input("Enter Your Second Value :",))
print("-"*50)
print("Sum({} And {})={}".format(a,b,a+b))
print("-"*50)
print("-"*50)
print("Sub({} And {})={}".format(a,b,a-b))
print("-"*50)
print("-"*50)
print("Mul({} And {})={}".format(a,b,a*b))
print("-"*50)
print("-"*50)
print("Div({} And {})={}".format(a,b,a/b))
print("-"*50)
print("-"*50)
print("Quetient({} And {})={}".format(a,b,a//b))
print("-"*50)
print("-"*50)
print("Remainder({} And {})={}".format(a,b,a%b))
print("-"*50)
print("Exponetiation({} And {})={}".format(a,b,a**b))
print("-"*50)